openapi: 3.0.0
info:
  title: Tantsaha & Co
  description: Une API REST pour gérer la communauté croissante de ceux qu'on appelle les « Tantsaha ».
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /collectivity:
    post:
      summary: Creer une nouvelle collectivite
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/CollectiviteCreation'
      responses:
        201:
          description: Collectivite cree avec succes
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Collectivite'
        400:
          description: Echec dans le cas ou les conditions ne sont pas respectees
          content:
            text/plain:
              example: "Vous devez avoir au moins 10 membres avec 5 d'une ancienete de 6 mois"

  /members:
    post:
      summary: Creer un nouveau membre
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NouveauMembre'
      responses:
        201:
          description: Membre cree
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Membre'
        400:
          $ref: '#/components/responses/BadRequest'

  /collectivity/{id}/members:
    post:
      summary: Ajouter un membre dans une collectivite
      parameters:
        - $ref: '#/components/parameters/CollectiviteId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdhesionMembre'
      responses:
        201:
          description: Membre ajoute
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'

  /collectivity/{id}/cotisations:
    post: 
      summary: create a new cotisation to pay
      parameters:
        - $ref: '#/components/parameters/CollectiviteId'
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/CotisationCreation'
      responses:
        201:
          description: Cotisation cree
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Cotisation'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
    get:
      summary: obtenir des infos sur toues les cotisations
      parameters:
        - $ref: '#/components/parameters/CollectiviteId'
      responses:
        200:
          description: Liste de toutes les cotisations
          content:
            application/json:
              schema:  
                type: array
                items:
                  $ref: '#/components/schemas/Cotisation'
        404:
          $ref: '#/components/responses/NotFound'
  /collectivity/{id}/cotisations/{cotisationId}:
      get:
        summary: Obtenir info sur une cotisation
        parameters:
          - $ref: '#/components/parameters/CollectiviteId'
          - $ref: '#/components/parameters/CotisationId'
        responses:
          200:
            description: La collectivite
            content:
              application/json:
                schema:  
                  $ref: '#/components/schemas/Cotisation'
          404:
            $ref: '#/components/responses/NotFound'
      patch:
        summary: Mettre a jour une cotisation
        parameters:
          - $ref: '#/components/parameters/CollectiviteId'
          - $ref: '#/components/parameters/CotisationId'
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CotisationUpdate'
        responses:
          200:
            description: cotisation mise a jour
            content:
              application/json:
                schema:  
                  $ref: '#/components/schemas/Cotisation'
          400:
            $ref: '#/components/responses/BadRequest'
          404:
            $ref: '#/components/responses/NotFound'
      delete:
        summary: Supprimer une cotisation
        parameters:
          - $ref: '#/components/parameters/CollectiviteId'
          - $ref: '#/components/parameters/CotisationId'
        responses:
          204:
            description: Cotisation supprimee
          400:
            $ref: '#/components/responses/BadRequest'
          404:
            $ref: '#/components/responses/NotFound'
  /collectivity/{id}/paiements:
    post:
      summary: creer un nouveau paiementType
      parameters:
      - $ref: '#/components/parameters/CollectiviteId'
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/PaiementCreation'
      responses:
        201:
          description: Paiement enregistere
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Paiement'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'

  /collectivity/{id}/activites:
    post: 
      summary: Creer une nouvelle activite 
      parameters:
        - $ref: '#/components/parameters/CollectiviteId'
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/ActiviteCreation'
      responses:
        201:
          description: activite cree
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Activite'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
    get:
      summary: Lister toutes les activites de la collectivites 
      parameters:
        - $ref: '#/components/parameters/CollectiviteId'
      responses:
        200:
          description: Liste des toutes les activites
          content:
            application/json:
              schema:  
                type: array
                items: 
                  $ref: '#/components/schemas/Activite'
        404:
          $ref: '#/components/responses/NotFound'
  /collectivity/{id}/activites/{activiteId}:
    get:
      summary: Obtenir info sur une activite
      parameters:
        - $ref: '#/components/parameters/CollectiviteId'
        - $ref: '#/components/parameters/ActiviteId'
      responses:
        200:
          description: Activite demandee
          content:
            application/json:
              schema:  
                $ref: '#/components/schemas/Activite'
        404:
          $ref: '#/components/responses/NotFound'
    patch:
      summary: Mettre a jour une activite
      parameters:
        - $ref: '#/components/parameters/CollectiviteId'
        - $ref: '#/components/parameters/ActiviteId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActiviteUpdate'
      responses:
        200:
          description: Activite mise a jour
          content:
            application/json:
              schema:  
                $ref: '#/components/schemas/Activite'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
    delete:
      summary: Supprimer une activite
      parameters:
        - $ref: '#/components/parameters/CollectiviteId'
        - $ref: '#/components/parameters/ActiviteId'
      responses:
        204:
          description: Activite supprimee
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'

components:
  parameters:
    CollectiviteId:
      name: id
      in: path
      required: true
      schema:
        type: integer
    CotisationId:
      name: cotisationId
      in: path
      required: true
      schema:
        type: integer

    MembreId:
      name: id
      in: path
      required: true
      schema:
        type: integer
    ActiviteId:
      name: activiteId
      in: path
      required: true
      schema:
        type: integer

  responses:
    BadRequest:
      description: Requete invalide
      content:
        text/plain:
          example: "Erreur de validation"
    NotFound:
      description: Ressource non trouvee
      content:
        text/plain:
          example: "Ressource non trouvee"

  schemas:
    
    ActiviteCreation:
      type: object
      properties:
        titre:
          type: string
          example: 'Reunion'
        type: 
          $ref: '#/components/schemas/ActiviteType'
        estOuvertATous:
          type: boolean
        obligatoirePour:
          type: array
          items:
            $ref: '#/components/schemas/Role'
        date:
          type: string
          format: date
        recurrence: 
          $ref: '#/components/schemas/ActiviteRecurrence'
    
    ActiviteType:
      type: string
      enum:
        - ASSEMBLE_GENERALE
        - FORMATION_OBLOGATOIRE
        - EXCEPTIONNELLE

    ActiviteRecurrence:
      type: object
      properties: 
        semaine: 
          type: integer
          minimum: 1
          maximum: 5
        jour:
          $ref: '#/components/schemas/JourDeSemaine'
    
    JourDeSemaine: 
      type: string
      enum:
        - LUNDI
        - MARDI
        - MERCREDI
        - JEUDI
        - VENDREDI
        - SAMEDI
        - DIMANCHE

    Activite: 
      allOf:
        - $ref: '#/components/schemas/ActiviteCreation'
        - type: object
          properties:
           id:
            type: integer
            example: 1

    ActiviteUpdate:
      type: object
      properties:
        titre:
          type: string
          example: 'Reunion'
        type: 
          $ref: '#/components/schemas/ActiviteType'
        estOuvertATous:
          type: boolean
        obligatoirePour:
          type: array
          items:
            $ref: '#/components/schemas/Role'
        date:
          type: string
          format: date
        recurrence: 
          $ref: '#/components/schemas/ActiviteRecurrence'

    PaiementCreation:
      type: object
      properties:
        membreId: 
          type: integer
          example: 1
        montant:
          type: number
          format: decimal
          minimum: 0
          example: 67000
        transactionType: 
          $ref: "#/components/schemas/TransactionType"
        transactionReference:
          type: string
          example: '20260420.1415MG'
        destinataireId:
          type: string
          example: '034 12 345 67'
        paiementType: 
          $ref : '#/components/schemas/PaiementType'
        description:
          type: string
          example: "Paiement d'adhesion noveau membre"
        cotisationId:
          type: integer
          example: 1
        activiteId: 
          type: integer
          example: 1
    
    Paiement: 
      allOf:
        - $ref: '#/components/schemas/PaiementCreation'
        - type: object
          properties:
            id:
              type: integer
              example: 1

    TransactionType:
      type: string
      enum:
        - CASH
        - MOBILE_MONEY
        - VIREMENT
    
    PaiementType: 
      type: string
      enum: 
        - COTISATION_PERIODIQUE
        - COTISATION_EXCEPTIONNELLE
        - VERSEMENT_FEDERATION
        - ADHESION 
        - ACTIVITE
        - FORMATION
        - AUTRE
    
    CollectiviteBaseComponent:
      type: object
      properties:
        specialite:
          type: string
          example: "Manioc"
        ville:
          type: string
          example: 'Ambatondrazaka'
    
    CollectiviteCreation:
      allOf:
        - $ref: '#/components/schemas/CollectiviteBaseComponent'
        - type: object
          properties:
            autorisation:
              $ref: '#/components/schemas/Autorisation'
            membres:
              type: array
              items:
                $ref: '#/components/schemas/NouveauMembre'
              minItems: 10
    
    Collectivite: 
      allOf:
        - $ref: '#/components/schemas/CollectiviteBaseComponent'
        - type: object
          properties:
            nom:
              type: string
              example: 'COllectivite manioc du sud'
            membres:
              type: array
              items: 
                $ref: '#/components/schemas/Membre'
    
    NouveauMembre:
      type: object
      properties:
        nom:
          type: string
          example: 'John'
        prenom:
          type: string
          example: 'Doe'
        adresse:
          type: string
          example: 'LOT 67 BIS'
        metier:
          type: string
          example: 'Agriculteur'
        role: 
          $ref: '#/components/schemas/Role'
        telephone:
          type: string
          example: '032 01 234 56'
        email:
          type: string
          format: email
          example: 'johndoe@gmail.com'
    
    Membre:
      allOf:
        - $ref: '#/components/schemas/NouveauMembre'
        - type: object
          properties:
            dateAdhesion:
              type: string
              format: date
              example: '2026-04-20'
    
    Role:
      type: string
      enum:
        - PRESIDENT
        - VICE_PRESIDENT
        - TRESORIER
        - SECRETAIRE
        - CONFIRME
        - JUNIOR
    
    Autorisation:
      type: object
      properties:
        id:
          type: integer
          example: 1
        titre:
          type: string
          example: 'Autorisation 2026/12/56'
        dateCreation:
          type: string
          format: date
          example: '2026-04-20'
        details:
          type: string
    
    AdhesionMembre:
      type: object
      properties:
        membreId:
          type: integer
          example: 1
        parrainId:
          type: integer
          example: 2
    
    CotisationCreation:
      type: object
      properties:
        titre:
          type: string
          example: 'Maintenance infrastructure'
        montant:
          type: number
          example: 15000
        type:
          $ref: '#/components/schemas/CotisationType'
    
    CotisationType:
      type: string
      enum:
        - MENSUEL
        - ANNUEL
        - PONCTUEL
    
    Cotisation: 
      allOf:
        - $ref: '#/components/schemas/CotisationCreation'
        - type: object
          properties:
            id:
              type: integer
              example: 1
            commencerLe:
              type: string
              format: date
    
    CotisationUpdate:
      type: object
      properties:
        titre:
          type: string
          example: 'Operation sandwiiich'
        montant:
          type: number
          example: 4000